name: Build QtScrcpy for Windows
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
    - name: Install MSVC Build Tools
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vswhere-version: 'latest'
    - name: Install Ninja Build System
      run: |
        choco install ninja -y
        choco install python2 -y
        refreshenv
    - name: Build QtScrcpy
      run: |
        cd QtScrcpy
        mkdir build && cd build
        cmake -G "Ninja" -DCMAKE_PREFIX_PATH=C:/Qt/Qt5.15.2/5.15.2/msvc2019_64/ -DCMAKE_BUILD_TYPE=Release -Dprebuilt_server="" ..
        ninja
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: QtScrcpy Windows Build
        path: QtScrcpy/build/QtScrcpy.exe
